[package]
name = "flui"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive", "env"] }
flightaware = { version = "0.1.0", path = "../flightaware" }
reqwest = "0.12.24"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
